
CREATE DATABASE ATIVIDADE_TIGGER_CINCO;

USE ATIVIDADE_TIGGER_CINCO;

CREATE TABLE tb_funcionarios (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(255),
  CARGO VARCHAR(255)
);


CREATE TABLE tb_dependentes (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME_DEPENDENTE VARCHAR(255),
  FUNCIONARIO_ID INT,
  FOREIGN KEY (FUNCIONARIO_ID) REFERENCES tb_funcionarios(ID)
);


DELIMITER //

CREATE TRIGGER tg_excluir_dependentes
AFTER DELETE ON tb_funcionarios
FOR EACH ROW
BEGIN
    DELETE FROM tb_dependentes WHERE FUNCIONARIO_ID = OLD.ID;
END //

DELIMITER ;


INSERT INTO tb_funcionarios (NOME, CARGO) VALUES ('Gabriel', 'Cantor');
INSERT INTO tb_funcionarios (NOME, CARGO) VALUES ('Jessica', 'Atriz');


INSERT INTO tb_dependentes (NOME_DEPENDENTE, FUNCIONARIO_ID) VALUES ('Kaua', 1);
INSERT INTO tb_dependentes (NOME_DEPENDENTE, FUNCIONARIO_ID) VALUES ('Daniel', 2);

DELETE FROM tb_funcionarios WHERE ID = 1;

SELECT * FROM tb_dependentes;
