CREATE DATABASE ATIVIDADE_TIGGER_TRES;

USE ATIVIDADE_TIGGER_TRES;

CREATE TABLE Produtos (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME_PRODUTO VARCHAR(255) NOT NULL,
  QUANT_ESTOQUE INT NOT NULL
);

DELIMITER //

CREATE TRIGGER tg_atualizar_estoque_venda
AFTER INSERT ON VENDAS
FOR EACH ROW
BEGIN
    UPDATE Produtos
    SET QUANT_ESTOQUE = QUANT_ESTOQUE - NEW.QUANT_VENDIDA
    WHERE ID = NEW.PRODUTO_ID;
END //

DELIMITER ;

INSERT INTO Produtos (NOME_PRODUTO, QUANT_ESTOQUE) VALUES ('Chocolate', 10);


CREATE TABLE Vendas (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PRODUTO_ID INT,
  QUANT_VENDIDA INT,
  FOREIGN KEY (PRODUTO_ID) REFERENCES Produtos(ID)
);

INSERT INTO Vendas (PRODUTO_ID, QUANT_VENDIDA) VALUES (1, 5);

SELECT * FROM Produtos;
