CREATE DATABASE ATIVIDADE_QUATRO;

USE ATIVIDADE_QUATRO;

CREATE TABLE Produtos (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME_PRODUTO VARCHAR(255) NOT NULL,
  PRECO DECIMAL(10, 2) NOT NULL
);

INSERT INTO Produtos (NOME_PRODUTO, PRECO) VALUES
('Sapato', 150.00),
('Calça', 80.50),
('Vestido', 120.75),
('Blusa', 90.25),
('Moletom', 200.00);

CREATE VIEW vw_produtos_caros AS
SELECT NOME_PRODUTO
FROM Produtos
WHERE PRECO > 100.00;

SELECT * FROM vw_produtos_caros;
