CREATE DATABASE ATIVIDADE_TIGGER_DOIS;

USE ATIVIDADE_TIGGER_DOIS;

CREATE TABLE Produtos (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME_PRODUTO VARCHAR(255) NOT NULL,
  PRECO DECIMAL(10, 2) NOT NULL
);

DELIMITER //

CREATE TRIGGER tg_aumentar_preco_produto
BEFORE UPDATE ON Produtos
FOR EACH ROW
BEGIN
    SET NEW.PRECO = NEW.PRECO * 1.10;
END //

DELIMITER ;

INSERT INTO Produtos (NOME_PRODUTO, PRECO) VALUES ('Blusa', 100.00);

UPDATE Produtos SET PRECO = 120.00 WHERE ID = 1;

SELECT * FROM Produtos;


